---
- name: Builders machine prepare
  hosts: tag_Name_builder
  remote_user: ubuntu
  become: yes
  gather_facts: False

  tasks:
    - name: Ensure docker is present
      apt:
        name: docker.io
        state: present

    - name: Ensure docker is running
      service:
        name: docker
        state: started

- name: Prod machines prepare
  hosts: tag_Name_prod
  become: yes

  tasks:
    - name: Ensure docker is present
      apt:
        name: docker.io
        state: present

    - name: Ensure docker is running
      service:
        name: docker
        state: started